In [59]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

In [60]:
df=pd.read_csv(r"C:\Users\Anna1\OneDrive\UNCC Classes\DTSC 1301\CSV Datasets\student_survey.csv")
df.head()

,student_id,age,height_cm,transportation,on_campus,satisfaction,study_hours,passed
0,101,18,165.2,Car,No,High,6.5,Yes
1,102,19,172.8,Bus,Yes,Medium,4.0,Yes
2,103,20,168.5,Walk,Yes,Low,2.5,No
3,104,21,180.1,Car,No,High,7.0,Yes
4,105,22,175.4,Bus,Yes,Medium,5.0,Yes

In [61]:
#One-hot encode transportation
transport_encoder= OneHotEncoder(sparse_output=False)

transport_encoded= transport_encoder.fit_transform(df[["transportation"]])

In [62]:
transport_df= pd.DataFrame(transport_encoded,
columns = transport_encoder.get_feature_names_out(["transportation"])
)

In [63]:
transport_df

    transportation_Bus  transportation_Car  transportation_Walk
0                  0.0                 1.0                  0.0
1                  1.0                 0.0                  0.0
2                  0.0                 0.0                  1.0
3                  0.0                 1.0                  0.0
4                  1.0                 0.0                  0.0
5                  0.0                 0.0                  1.0
6                  0.0                 1.0                  0.0
7                  1.0                 0.0                  0.0
8                  0.0                 1.0                  0.0
9                  0.0                 0.0                  1.0
10                 1.0                 0.0                  0.0
11                 0.0                 1.0                  0.0
12                 0.0                 0.0                  1.0
13                 0.0                 1.0                  0.0
14                 1.0                 0.0                  0.0
15                 0.0                 0.0                  1.0
16                 0.0                 1.0                  0.0
17                 1.0                 0.0                  0.0
18                 0.0                 0.0                  1.0
19                 1.0                 0.0                  0.0

In [64]:
#Encode on campus

campus_encoder = OrdinalEncoder(categories=[["No","Yes"]])

In [65]:
df["on_campus"]=campus_encoder.fit_transform(df[["on_campus"]])

In [66]:
#Encode satisfaction

satisfaction_encoder= OrdinalEncoder(categories=[["Low","Medium","High"]])
df["satisfaction"]=satisfaction_encoder.fit_transform(df[["satisfaction"]])

In [67]:
#Encode passed

passed_encoder = LabelEncoder()
df["passed"]=passed_encoder.fit_transform(df[["passed"]])

c:\Users\Anna1\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [68]:
#Remove original transportation column

df=df.drop(columns=["transportation"])

In [74]:
#Add the encoded 
df= pd.concat([df.reset_index(drop=True), transport_df.reset_index(drop=True)],axis=0
)

In [75]:
df.head()

,student_id,age,height_cm,on_campus,satisfaction,study_hours,passed,transportation_Bus,transportation_Car,transportation_Walk
0,101.0,18.0,165.2,0.0,2.0,6.5,1.0,0.0,1.0,0.0
1,102.0,19.0,172.8,1.0,1.0,4.0,1.0,1.0,0.0,0.0
2,103.0,20.0,168.5,1.0,0.0,2.5,0.0,0.0,0.0,1.0
3,104.0,21.0,180.1,0.0,2.0,7.0,1.0,0.0,1.0,0.0
4,105.0,22.0,175.4,1.0,1.0,5.0,1.0,1.0,0.0,0.0